import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dataPath = resolve(root, 'src/data/resume-data.json');
const previewDirectory = resolve(root, 'resume-tmp');
const publish = process.argv.includes('--publish');
const outputPath = resolve(previewDirectory, 'resume.tex');
const publishPath = resolve(root, 'src/data/resume.tex');
const selectAll = process.argv.includes('--all') || !process.stdin.isTTY;
const readline = selectAll ? null : createInterface({ input: process.stdin, output: process.stdout });

const data = JSON.parse(await readFile(dataPath, 'utf8'));
const allIndexes = (items) => items.map((_, index) => index);
const texEscapes = {
  '\\': '\\textbackslash{}', '&': '\\&', '%': '\\%', '$': '\\$', '#': '\\#',
  '_': '\\_', '{': '\\{', '}': '\\}', '→': '$\\rightarrow$',
};
const monthIndexes = Object.fromEntries([
  'jan', 'feb', 'mar', 'apr', 'may', 'jun',
  'jul', 'aug', 'sep', 'oct', 'nov', 'dec',
].map((month, index) => [month, index]));

const toTex = (value) => [...value].map((character) => texEscapes[character] ?? character).join('');

function parseSelection(value, itemCount) {
  const answer = value.trim().toLowerCase();
  if (!answer || answer === 'all') return allIndexes(Array(itemCount));
  if (answer === 'none') return [];

  const selected = [...new Set(answer.split(',').map((part) => Number(part.trim()) - 1))]
    .filter((index) => Number.isInteger(index) && index >= 0 && index < itemCount);
  if (!selected.length) throw new Error('Choose comma-separated item numbers, “all”, “none”, or press Enter for all.');
  return selected;
}

async function choose(label, items, format) {
  if (selectAll) return allIndexes(items);
  console.log(`\n${label}`);
  items.forEach((item, index) => console.log(`  ${index + 1}. ${format(item)}`));

  while (true) {
    try {
      return parseSelection(await readline.question('Select numbers (Enter = all): '), items.length);
    } catch (error) {
      console.log(error.message);
    }
  }
}

function formatDuration(dates) {
  const match = dates.match(/^([A-Za-z]{3})\.?\s+(\d{4})\s*-\s*(Present|([A-Za-z]{3})\.?\s+(\d{4}))$/);
  if (!match) return '';

  const startMonth = monthIndexes[match[1].toLowerCase()];
  const startYear = Number(match[2]);
  const end = match[3] === 'Present'
    ? new Date()
    : new Date(Number(match[5]), monthIndexes[match[4].toLowerCase()], 1);
  if (startMonth === undefined || Number.isNaN(startYear) || Number.isNaN(end.getTime())) return '';

  const totalMonths = Math.max(0, (end.getFullYear() - startYear) * 12 + end.getMonth() - startMonth);
  const years = Math.floor(totalMonths / 12);
  const months = totalMonths % 12;
  return `${years ? `${years}y` : ''}${years && months ? ' ' : ''}${months ? `${months}m` : ''}`;
}

function renderExperience(experience) {
  const duration = formatDuration(experience.dates);

  return String.raw`\resumeHeading
{${toTex(experience.role)}}
{${toTex(experience.company)} - ${toTex(experience.city)}}
{${toTex(experience.dates)}}
{${duration}}

\begin{itemize}
${experience.highlights.map((highlight) => `\\item ${toTex(highlight)}`).join('\n')}
\end{itemize}
\resumeFooting{}`;
}

function renderResume(experiences, skills) {
  const { contact, education, summary } = data;
  const renderedSkills = skills.length
    ? String.raw`\section{Technical Skills}

${skills.map(({ category, items }) => String.raw`\textbf{${toTex(category)}:}
${items.map(toTex).join(', ')}`).join('\n\n')}`
    : '';

  return String.raw`% This file is generated by yarn gen-resume. Edit src/data/resume-data.json instead.
\documentclass[10pt,letterpaper]{article}

\usepackage[top=0.43in,bottom=0.43in,left=0.65in,right=0.65in]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{montserrat}
\usepackage{microtype}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{xcolor}
\usepackage{hyperref}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}
\hypersetup{hidelinks}
\AtBeginDocument{\fontsize{9.25}{10.7}\selectfont}
\setlist[itemize]{leftmargin=1.25em,itemsep=0.5pt,topsep=1pt,parsep=0pt,partopsep=0pt}
\titleformat{\section}{\large\bfseries}{}{0em}{}[\vspace{-0.4em}\rule{\textwidth}{0.5pt}]
\titlespacing*{\section}{0pt}{5pt}{3pt}
\newcommand{\resumeHeading}[4]{\textbf{#1} \hfill \textcolor{gray}{\scriptsize #4}\hspace{0.35em}#3\\\textit{#2}}
\newcommand{\resumeFooting}[0]{\vspace{0.3em}}

\begin{document}

\begin{center}
    {\LARGE\bfseries ${toTex(contact.name)}}\\[3pt]
    ${toTex(contact.location)}
    \enspace$\cdot$\enspace
    \href{tel:${contact.phoneHref}}{${toTex(contact.phone)}}
    \enspace$\cdot$\enspace
    \href{mailto:${contact.email}}{${toTex(contact.email)}}
    \\[2pt]
    \href{https://chil.dev}{\textcolor{gray}{chil.dev}}
    \enspace$\cdot$\enspace
    \href{https://chil.dev/linkedin}{\textcolor{gray}{chil.dev}/LinkedIn}
    \enspace$\cdot$\enspace
    \href{https://chil.dev/github}{\textcolor{gray}{chil.dev}/GitHub}
\end{center}

\raggedright

\section{Summary}

${toTex(summary)}

\section{Experience}

${experiences.map(renderExperience).join('\n\n')}

${renderedSkills}

\section{Education}

\resumeHeading
{${toTex(education.institution)}}
{${toTex(education.degree)}}
{${toTex(education.dates)}}
{}

\end{document}
`;
}

function revealInFinder(path) {
  return new Promise((resolveReveal) => {
    const finder = spawn('open', ['-R', path], { stdio: 'ignore' });
    finder.once('error', () => {
      console.warn('Could not reveal the generated file in Finder.');
      resolveReveal();
    });
    finder.once('exit', () => resolveReveal());
  });
}

const experienceIndexes = await choose('Experiences', data.experiences, (entry) => `${entry.company} — ${entry.role}`);
const selectedExperiences = experienceIndexes.map((index) => data.experiences[index]);
const selectedSkills = [];

for (const group of data.skills) {
  const indexes = await choose(`Skills / ${group.category}`, group.items, (skill) => skill);
  if (indexes.length) selectedSkills.push({ category: group.category, items: indexes.map((index) => group.items[index]) });
}

try {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderResume(selectedExperiences, selectedSkills));
  console.log(`\nGenerated ${outputPath.replace(`${root}/`, '')} with ${selectedExperiences.length} experience(s) and ${selectedSkills.reduce((total, group) => total + group.items.length, 0)} skill(s).`);
  if (publish) {
    await copyFile(outputPath, publishPath);
    console.log(`Published ${publishPath.replace(`${root}/`, '')}.`);
  }
  await revealInFinder(outputPath);
} finally {
  readline?.close();
}
